
export const ADD_NEW_STAFF = 'ADD_NEW_STAFF';
export const STAFFS_LOADING ='STAFFS_LOADING';
export const STAFFS_FAILED ='STAFFS_FAILED';
export const UPDATE_STAFFS ='UPDATE_STAFFS';

export const DEPARTMENT_LOADING ='DEPARTMENT_LOADING';
export const DEPARTMENT_FAILED='DEPARTMENT_FAILED';
export const ADD_DEPARTMENT ='ADD_DEPARTMENT';

export const SALARY_LOADING='SALARY_LOADING';
export const SALARY_FAILED ='SALARY_FAILED';
export const ADD_SALARY ='ADD_SALARY';
